### ISSUE TITLE
Related tool: tinc

### ISSUE THREAD

**Issue by robbinch** [Gabriel439/haskell-nix#10]
Not really an issue, but you might be interested in tinc, which has experimental support for instantiating the entire Cabal install plan via Nix. See https://github.com/sol/tinc/blob/nixpkgs/NIX.md. It's far from polished but still a small step. Make sure to use the nixpkgs branch from sol/tinc when trying this out (or install via haskellPackages.tinc from nixpkgs).

**Comment by Gabriel439** [comment]
Fixed by 4e907817fd0812fb2e3ed760f089a078961f163b.  Feel free to expand on the initial description if there is anything else you would like me to mention
