### ISSUE TITLE
Project3 problem with config

### ISSUE THREAD

**Issue by Rizary** [Gabriel439/haskell-nix#14]
Hi,

I have setup my release.nix code like the following:

```

let
  config = rec {
    allowUnfree = true;
    allowBroken = true;
    packageOverrides = pkgs: rec {
      haskellPackages = pkgs.haskellPackages.override {
        overrides = haskellPackagesNew: haskellPackagesOld: rec {
          frontend =
	    haskellPackagesNew.callPackage ./default.nix {};
	  };
      };
    };

    permittedInsecurePackages = [ "webkitgtk-2.4.11" ];
  };

  pkgs = import <nixpkgs> { inherit config; };

in
  { frontend = pkgs.haskellPackages.frontend; }

```

then in my `shell.nix`, i insert this code `(import ./release.nix).frontend.env`

However, when i run `nix-shell -p haskell.compiler.ghcjs --command "cabal configure"`

I got the following error:

```

error: Package ‘ghcjs-0.2.0’ in ‘/nix/store/wr91a710329n2jzsfd3biykyjwxv8pbn-nixpkgs-17.09pre102933.26625c9/nixpkgs/pkgs/development/compilers/ghcjs/base.nix:108’ is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)

```

the question is, i had already set the `allowBroken = true;` on my release.nix, but why it seems i have not set the allowBroken yet. 

Does the approach is incorrect?

thank you.

**Comment by Gabriel439** [comment]
This is because `nix-shell` with the `--packages` or `-p` option ignores your `release.nix` file (even if you supply the file on the `nix-shell` command line).  That's why it doesn't pick up your `allowBroken = true` option.

**Comment by Rizary** [comment]
Thank you @Gabriel439. This tutorial is helpful. Will it continue? Because I am still cannot find the tutorial on how to change the compiler..

**Comment by dmjio** [comment]
@Rizary, if you'd like to change the `compiler`, you can pass it as a string argument to the derivation and use string interpolation to dynamically set the field name. 

```nix
{ compiler ? "ghc802" }:
  let
   config = {
     packageOverrides = pkgs: with pkgs.haskell.lib; {
       haskell.packages.${compiler} = pkgs.haskell.packages.${compiler}.override {
          overrides = self: super: rec {
            google-translate = buildStrictly (self.callPackage ./google-translate.nix { });
          };
        };
      };
   };
   in
     let
       pkgs = import <nixpkgs> { inherit config; };
       google-translate = pkgs.haskell.packages.${compiler}.google-translate;
     in { inherit google-translate; }
```

**Comment by Gabriel439** [comment]
I just added the instructions on changing the compiler in 419ecf3a1610cc8ded379db7bb7ae53b1a6ccab7

**Comment by Rizary** [comment]
Thank you @Gabriel439 it much clearer for me. Although I got an error for playing GHCJS :D

so I just posted in here : [http://stackoverflow.com/questions/42760779/missing-dependencies-when-run-nix-shell-with-ghcjs-compiler](url)

**Comment by dmjio** [comment]
@Rizary `tasty-ant-xml` needs to be jailbroken, or, you need to add the build dependencies it is looking for.

```nix
{ pkgs ? import <nixpkgs> {} }:
let
 ghcjsPackages = pkgs.haskell.packages.ghcjs.override {
   overrides = self: super: with pkgs.haskell.lib; { 
     tasty-ant-xml = 
       doJailbreak (addBuildDepends super.tasty-ant-xml [ super.directory super.filepath ]);
  };
}; in ghcjsPackages.callPackage ./default.nix {}
```
