### ISSUE TITLE
Shouldn't the docker image have its "Cmd" set to something non-null?

### ISSUE THREAD

**Issue by siers** [Gabriel439/haskell-nix#18]
I'm probably just missing something, but I expected the last command to work.

    project3 master % nix-build -A docker-container-small release2.nix
        /nix/store/s86imza199bw8dc9lv648w8zzf3cfp1z-docker-image-project3-container.tar.gz

    project3 master % ls -l
        total 68K
        drwxr-xr-x 2 4.0K Jun 13 23:52 cbits
        -rw-r--r-- 1  348 Jun 13 23:52 default.nix
        -rw-r--r-- 1 1.5K Jun 13 23:52 LICENSE
        -rw-r--r-- 1   82 Jun 13 23:52 Main.hs
        -rw-r--r-- 1  520 Jun 13 23:52 project3.cabal
        -rw-r--r-- 1  110 Jun 13 23:52 Project3.hs
        -rw-r--r-- 1  21K Jun 13 23:52 README.md
        -rw-r--r-- 1  436 Jun 13 23:52 release0.nix
        -rw-r--r-- 1  630 Jun 13 23:52 release1.nix
        -rw-r--r-- 1 1.9K Jun 13 23:52 release2.nix
        lrwxrwxrwx 1   82 Jun 17 16:07 result -> /nix/store/s86imza199bw8dc9lv648w8zzf3cfp1z-docker-image-project3-container.tar.gz

    project3 master % docker import result nix-haskell-test:latest
        sha256:7e57bf97c434974b0219d0dec5b2208319d666cbba07f1ae382f03d58bfa3e81

    project3 master % docker inspect nix-haskell-test:latest | grep -iE '(id|created|cmd|zn)'
        "Id": "sha256:7e57bf97c434974b0219d0dec5b2208319d666cbba07f1ae382f03d58bfa3e81",
        "Created": "2017-06-17T21:16:27.785807674Z",
            "Cmd": null,
            "Cmd": null,
                "DeviceId": "4260",

    project3 master % docker run nix-haskell-test:latest
        docker: Error response from daemon: No command specified.
        See 'docker run --help'.

**Comment by Gabriel439** [comment]
Try to do this:

```bash
$ mkdir tmp
$ cp result tmp
$ cd tmp
$ tar xzf result
$ cat */json
```

The purpose of this is to see if the `json` inside the `docker` archive had a `Cmd` configured

**Comment by Gabriel439** [comment]
For reference, here is what I get:

```
{
 "architecture": "amd64",
 "config": {
  "Cmd": [
   "\/nix\/store\/m0mmcqd8fpjc5j176qxdjzclnw4l5rvs-project3-1.0.0\/bin\/project3"
  ]
 },
 "created": "1970-01-01T00:00:01Z",
 "os": "linux",
 "checksum": "tarsum.v1+sha256:0166c8fa0c461fe0d046c622ebac53620ab3d48fb4ad303c5dfa62da87ae118c",
 "id": "f3c8fdc8a039108a7072e121d7f9b61b4c95016179118a017988bbb3b74b5b58",
 "Size": 28600320
}
```

... which shows that there is a `Cmd` in there, although perhaps it is still a malformed image

**Comment by siers** [comment]
Ah, the cmd is there and importing with `docker load -i result` worked, so it's my fault, but the `README.md` doesn't show what to do with the image, though.

Googling "docker import cmd" found me this, which is about the same issue. https://github.com/moby/moby/issues/8334

    s|code/cache/haskell-nix master % docker run -it project3-container
    tar_open failed

**Comment by Gabriel439** [comment]
Yeah, I will update the tutorial to give an example of using the image, then

**Comment by siers** [comment]
Thank you! (P.S. I will leave the decision to close the issue to you.)

**Comment by Gabriel439** [comment]
I'll leave it open until I update the tutorial
