### ISSUE TITLE
Question about use of packageOverrides

### ISSUE THREAD

**Issue by adelbertc** [Gabriel439/haskell-nix#23]
In your examples the way you do overrides and adding project attributes (e.g. `project1`) is with `packageOverrides` which uses the `config` attribute when importing `nixpkgs`. However when you use `config` on import then overrides in `~/.config/nixpkgs/config.nix` are no longer considered.

On one hand this is good since you want all configuration local to the project so there's no ambient state leaking in on your system. But on the other hand if you need say, a fork of some tooling (ghc-mod, intero, whatever) available in nix-shell then by using `packageOverrides` in your project you no longer get the tooling you need, unless you include it in your project build files which is kind of weird.

An alternative I have seen is to do overrides using something like:

```nix
overrideHaskellPkgs = self: super: {
  haskellPackages = myOverrides self super;
};

pkgs = fix' (extends overrideHaskellPkgs ...)
```

which is how haskellPackages does things in Nix I believe. This way you get overrides but also the ability to preserve your config.

Curious to hear your thoughts.

**Comment by Gabriel439** [comment]
@adelbertc: So I decided to introduce how to do this in the context of a new tutorial section that covers automating dependency management and composing extending functions.  Could you check out this pull request and let me know if that covers your use case:

https://github.com/Gabriel439/haskell-nix/pull/24

The part that specifically addresses what you asked about is at the very end of the section

**Comment by adelbertc** [comment]
Hey @Gabriel439 , sorry for taking a while to get back.

I just read through #24 which was very instructive, though I don't think it addresses my question. Since you're doing everything through `config` that means when Nix runs anything in `~/.config/nixpkgs/config.nix` is no longer picked up. Some stuff in the config that you may want picked up are packageOverrides for tooling (e.g. ghc-mod, intero) that probably don't belong in the build for a project. Was wondering how you would handle that.

(But I still think you should merge #24 :-) )

**Comment by Gabriel439** [comment]
@adelbertc: Since version 17.03 `nixpkgs` provides a feature called overlays, which I think might solve your problem:

https://nixos.org/nixpkgs/manual/#chap-overlays

Specifically, if you specify your overrides in `~/.config/nixpkgs/overlays/` then I believe they would be picked up automatically without conflicting with the explicit `config`

**Comment by adelbertc** [comment]
Oo that looks interesting, I'll give that a shot. Thank you!

**Comment by Gabriel439** [comment]
You're welcome! :)
