### ISSUE TITLE
Question: missing `exec` in a docker build with `dockerTools.buildImage`

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/haskell-nix#26]
When running a docker using this [configuration](http://nixpaste.lbr.uno/GYGx-TJy?nix) I have got this error:
```
→ docker run -v ~/.config/cicd:/.config/cicd:ro pi3r/cicd-shell prod facts            
cicd: /bin/sh: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
I am still poking around the internet but I haven't found what I am missing yet. Any idea ?

**Comment by Gabriel439** [comment]
Actually, the error message is formatted in a confusing way.  It's actually `/bin/sh` that is missing from your container.  More generally, any time you see an error message of the form:

```
${SOME_PROGRAM}: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

... it means that `${SOME_PROGRAM}` is missing

**Comment by PierreR** [comment]
Thanks for the info. My first try was actually to add `super.bash` in `executableSystemDepends`.

I was expecting it to give `bin/sh` in the docker. Do I need to set something else like an environment variable ?

**Comment by PierreR** [comment]
I was expect this snippet : 
```
{ nixpkgs ? import ~/.config/nixpkgs/pin.nix, compiler ? "default" }:

let
  inherit (nixpkgs) pkgs;
  hlib = pkgs.haskell.lib;
  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};
  drv = hlib.overrideCabal
  ( hlib.justStaticExecutables (haskellPackages.callPackage ./. {
    protolude = haskellPackages.protolude_0_2;
  }))
  ( oldDerivation: {
    executableSystemDepends = [ pkgs.bash] ;
  });
in

if pkgs.lib.inNixShell then drv.env else drv
```
to add bash and sh in `result/bin`

**Comment by PierreR** [comment]
If I understand this correctly, I should not use `executableSystemDepends ` but instead tweak the `scratch` docker image to get everything I need.

**Comment by Gabriel439** [comment]
@PierreR: Nix distinguishes between build-time dependencies and run-time dependencies.  `executableSystemDepends` (and all of the other `*Depends` fields) are all build-time dependencies, meaning that they will be present when building the package, but not necessarily present when running the package

The way you would make `bash` available on the image is to change the derivation that assembles the image, as you suggested
