### ISSUE TITLE
Explain how Haskell package sets and compiler versions are linked

### ISSUE THREAD

**Issue by tekul** [Gabriel439/haskell-nix#32]
I've been trying to convert a stack-based project to nix today and ran into a problem. Nix is generally presented as being similar to stack in that the packages are all guaranteed to build together. We're also told that `haskellPackages` is just a shortcut for writing `haskell.packages.<compiler-version>` and that we can switch to another compiler just by using a parameter here.

I assumed that switching to `ghc821` (which I was already using with a stack nightly snapshot) would give me a set of packages that are compatible with this compiler, but this isn't the case. Specifically `hasql` has a test dependency on `rebase-1.0.8` which has a bound on `base < 4.10` and they won't build together. At this point I'm not really sure how the package set for this compiler (or indeed any) is determined. Is the Haskell package set only specific to one version of nixpkgs and only guaranteed to work with the default compiler? Or do you get a different Haskell package set if you switch compilers while still on the same version of nixpkgs?

The `project 1` README seems to be where curated packages sets are discussed. Perhaps an explanation of where they come from and how (or if) they depend on the chosen compiler could be added here?

**Comment by PierreR** [comment]
From my experience, the guarantee you are talking about is only true for the default compiler version. If you want to make it work for other compilers you usually need to tweak (override) package properties locally (and optionality share these with PRs).

For `ghc821` in particular, it would  work on my local settings with a bunch of overrides such as `QuickCheck = hlib.dontCheck(_hpkgs.QuickCheck_2_10_0_1);`.

I am using `overlays` to customize `nixpkgs` (`haskell-nix` suggests another mechanism).  The deleted comment from this commit will show you how to get there:  https://github.com/CIRB/nixpkgs-config/commit/2113e4544f57a70d6e37c83fd81ec453ea72f006#diff-39144f692cdc8c76a79c6702ddfa79e0

I hope it helps.

**Comment by tekul** [comment]
Hey, thanks. That is pretty helpful and I eventually managed to get something working with overlays at the project level. The main problem I had is that having a global overlay set (in `.config/nixpkgs`) seems to be incompatible with using the `packageOverrides` approach detailed here. As soon as I added the overlay file (which overrode Haskell packages for ghc821), my `release.nix` would no longer build - the project name attribute could no longer be found. Using an overlay locally in the project works OK, and I guess is effectively the same as using `packageOverrides`. However, if I set the overlays locally, then the global one seems to be ignored. This is pretty much as expected from the [manual's description of loading overlays](https://nixos.org/nixpkgs/manual/#sec-overlays-install).

I'd like to work out how to specify overrides for ghc821 compatibility at a global level and combine those with more project-specific ones at the project level. That way someone can build my project using the default compiler (and its standard dependencies) but I can still work against ghc821 without polluting the project build with overrides which are only there because of problems with the curated packages set building against ghc821.

**Comment by vyp** [comment]
> I'd like to work out how to specify overrides for ghc821 compatibility at a global level and combine those with more project-specific ones at the project level.

Maybe open an issue at nixos/nixpkgs for this? (Or look for any previous similar issues.)

**Comment by PierreR** [comment]
@tekul I have a shell.nix file in my project that looks like this:
```
{ compiler ? "default" }:

let
  _pkgs = import <nixpkgs> { };
  nixpkgs = builtins.fromJSON (builtins.readFile ./.nixpkgs.json);
  src = _pkgs.fetchFromGitHub {
    owner = "NixOS";
    repo  = "nixpkgs";
    inherit (nixpkgs) rev sha256;
  };

  pkgs = import src { };
  hlib = pkgs.haskell.lib;
  haskellPackages = if compiler == "default"
                       then pkgs.haskellPackages
                       else pkgs.haskell.packages.${compiler};
  drv = hlib.dontHaddock (haskellPackages.callPackage ./. {
    megaparsec = haskellPackages.megaparsec_6_2_0;
    hspec-megaparsec = haskellPackages.hspec-megaparsec_1_0_0;
  });
in

if pkgs.lib.inNixShell then drv.env else drv
```
You can pass the `ghc821` compiler at the command line with `--argstr` when using `nix-build` or `nix-shell`.

**Comment by tekul** [comment]
For reference I think I've managed to solve my problem after reading about the use of `extend` in [this issue](https://github.com/NixOS/nixpkgs/issues/25887). This allows me to define global package overrides to solve issues for specific compiler versions (such as the rebase/ghc821 issue mentioned above) and compose these with my local project overrides. So I have [this overlay](https://github.com/tekul/dotfiles/blob/6af670efff685ddf6fdf4af1128e68637475e022/nixpkgs/overlays/haskell.nix) as my global Haskell setup, and I can also use `extend` [in my local project ](https://github.com/ThreeMinuteLearning/my3ml/blob/94482c90e6700970bcd997364c1c7fd7a76050bb/release.nix#L6)
 to make additional package changes.
