### ISSUE TITLE
Project 1 is not working anymore ?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/haskell-nix#34]
I am trying to follow the examples of project 1 but release1.nix to release4.nix, are all failing with:

```
→ nix-build --attr project1 release4.nix                                                                                                                                                                                                   
error: attribute ‘project1’ missing, at /home/vagrant/projects/hub/haskell-nix/project1/release4.nix:22:16
```
`release0.nix` is ok and `release5.nix` is ok.

Maybe a recent change (I am using the latest stable channel of 17.09) has deprecated the exposed usage in favor of overlays or something alike ?

**Comment by Gabriel439** [comment]
I can't reproduce this problem and I'm on unstable.  Are you sure you haven't modified that file?  I'm asking because line 22 column 16 doesn't point to the `project1` attribute for that file in `master`

**Comment by PierreR** [comment]
That's weird. I am on nixos (and do have some user defined overlays in ~/.config/nixpkgs/overlays).

I have just checked again and the repository is green. line 22 16 is pointing exactly on the 'p' character of https://github.com/Gabriel439/haskell-nix/blob/master/project1/release4.nix#L22. 

I am using overlays locally instead of config to solve the problem : 
```
let
  hoverlays = self: super:

  pkgs = import <nixpkgs> {
    overlays = [ hoverlays];
  };
in
```

**Comment by Gabriel439** [comment]
Right, but the `project1` attribute is not missing from `pkgs`.  It would be missing from either the top-level record or from `haskellPackages`.  That's what makes the error message suspicious

**Comment by Gabriel439** [comment]
Or to put it another way: your error message would make more sense if your command line had been:

```bash
$ nix-build --attr project1.project release4.nix                                                                                                                                                                                                   
```

**Comment by PierreR** [comment]
I really don't see what's wrong on my side (I am working with a green unmodified local clone). 

I am closing the issue. I guess it must be something so stupid that I don't see it. Working with overlays solves the problem for me.

Thanks for checking that up so quickly.

**Comment by Gabriel439** [comment]
You're welcome!  Sorry I couldn't be more help, but I'm glad that you have a workaround.  If other people run into this issue they can feel free to reopen this
