### ISSUE TITLE
Detail stack vs cabal vs nix cabal defaults

### ISSUE THREAD

**Issue by kanishka-azimi** [Gabriel439/haskell-nix#35]
When invoking cabal, nix selects default behavior for cabal that might not match what someone would expect when coming from stack or cabal w/o nix. Consider spelling out main differences.

**Comment by mpickering** [comment]
What do you mean by this? Nix doesn't invoke `cabal` when building a package. It compiles the `Setup.hs` script and uses that.

**Comment by kanishka-azimi** [comment]
I guess I should say settings used with cabal the library.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-builder.nix - for the longer set of args, discussing defaults, such as doCheck.

**Comment by kanishka-azimi** [comment]
I probably won't get around to providing a detailed edit suggestion for a while, and this might be too far off topic generally. Closing.
