### ISSUE TITLE
Question: add a link to haskell-overridez?

### ISSUE THREAD

**Issue by adetokunbo** [Gabriel439/haskell-nix#49]
After reading [Advanced Dependency Management](https://github.com/Gabriel439/haskell-nix/tree/master/project4) and using it's ideas in some projects, I wrote [haskell-overridez](https://github.com/adetokunbo/haskell-overridez) to make it really easy to use this approach.

Feedback on the project would be great; perhaps I could also send a PR adding a link to it on  [Advanced Dependency Management](https://github.com/Gabriel439/haskell-nix/tree/master/project4) ?

**Comment by Gabriel439** [comment]
If you prefer I can mention it in the Related Tools section on the landing page:

https://github.com/Gabriel439/haskell-nix#related-tools

**Comment by adetokunbo** [comment]
That would be great, thank you!
