### ISSUE TITLE
Native runtime dependencies question

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/haskell-nix#50]
Does the native dependencies section applies to native runtime dependencies on executables ?

For instance I have a haskell executable that uses `turtle` under the hood. Turtle is going to call two external executable: [jq ](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/jq/default.nix)and [pepper](https://github.com/NixOS/nixpkgs/tree/master/pkgs/tools/admin/salt/pepper).

Is there an idiomatic way to make sure the closure of the derivation will contain both executables (while using `justStaticExecutables`. 

I have been trying this : http://nixpaste.lbr.uno/KdgmFXii?nix

Unfortunately when I try `nix run -f release.nix project` I will end up in a shell that doesn't include the `pepper` executable.

Also when I add `extra-libraries:     jq, pepper` to cabal I keep getting this error:

```
Setup: Missing dependency on a foreign library:
  * Missing C library: pepper
```
It is a bit confusing because `pepper` is just a python executable, not a C library.

Thanks for your help.

**Comment by Gabriel439** [comment]
@PierreR: The `extra-libraries` section is only for things that your Haskell program at build-time.  `cabal` does not have any section for specifying run-time dependencies for your program

I believe all you have to do is remove the `extra-libraries` line from your `.cabal` file

**Comment by PierreR** [comment]
@Gabriel439 Thanks. I will use `buildEnv` then to ensure all the deps are available.
