### ISSUE TITLE
Overlay example

### ISSUE THREAD

**Issue by rsoeldner** [Gabriel439/haskell-nix#58]
Hey,

this is my first try using overlays, according to #53 this is the recommended way now.

 It looks like nix is not able to find my `app` package, 
```
nix-build release.nix 
error: attribute 'app' missing, at /Users/rsoeldner/work/haskell-nix-overlay/release.nix:11:12
(use '--show-trace' to show detailed location information)
```
do I still need to override `haskell.packages` ?
The `default.nix` was generated by `cabal2nix . > default.nix`

```
{ compiler ? "ghc802" }:

let
  a = self: super:
      {   
        app = super.callPackage ./default.nix;
      };  

  overlays = [a];
  pkgs = import <nixpkgs> { inherit overlays; };
in { app = pkgs.haskell.packages.${compiler}.app; }
```

**Comment by PierreR** [comment]
@rsoeldner You need to do something alike:
```
  a = self: super:
    {
        haskellPackages = super.haskellPackages.override {
          overrides = hself: hsuper: rec {
             app = super.callPackage ./default.nix;
          };
      };
    }


```

**Comment by rsoeldner** [comment]
@PierreR thank you, from what I understood from https://nbp.github.io/slides/NixCon/2017.NixpkgsOverlays/?full#p1-prior-overlays this all `overrides` will be replaced by `overlays`.

I struggle understanding what pieces fit together, Is there a documentation about `overrides` accepting a function with two arguments returning a set ?

In my `shell.nix` I want to add the same GHC version with hoogle enabled, there should be an easy way adding _all_ packages to the hoogle search ?

**Comment by PierreR** [comment]
The overlays is replacing the `packageOverrides` idioms, so this part:
```
config = {
    packageOverrides = pkgs: rec {
```
I doesn't replace the `override` attribute.

**Comment by rsoeldner** [comment]
@PierreR Thank you, this makes sense.

Currently I'm at:

_release.nix_
```
compiler ? "ghc822" }:

 let 
  overlays = [(import ./custom-overlay.nix)];
  pkgs = import <nixpkgs> 
  {
    inherit overlays;
  };  
in
  { app = pkgs.haskellPackages.app;
  }
```

with the _custom-overlay.nix_
```
  self: super:
  {
    haskellPackages = super.haskellPackages.override  {
      overrides = hself: hsuper:
      {   
        app = super.callPackage ./default.nix;
      };  
    };  
  }
```

and the _shell.nix_
```
(import ./release.nix {}).app.env
```

But entering the `nix-shell` yields 
```
nix-shell 
error: value is a function while a set was expected, at /Users/rsoeldner/work/haskell-nix-overlay/shell.nix:1:1
(use '--show-trace' to show detailed location information)
```

Is this the right approach ?
And inside the _custom-overlay.nix_ shouldn't it  be a `hsuper.callPackage ???` ?

**Comment by sboosali** [comment]
(wait, doesn't callPackage need self (i.e. `hself`) to pick up on the new
packages?)

**Comment by Gabriel439** [comment]
Yeah, `custom-overlay.nix` should be:

```
  self: super:
  {
    haskellPackages = super.haskellPackages.override  {
      overrides = hself: hsuper:
      {   
        app = hself.callPackage ./default.nix;
      };  
    };  
  }
```

If you use `hsuper.callPackage` then `app` won't pick up any overrides you make to its dependencies

**Comment by rsoeldner** [comment]
@Gabriel439 this makes sense too.

```
nix-shell --show-trace
error: while evaluating the attribute 'app.env' at /Users/rsoeldner/work/haskell-nix-overlay/release.nix:10:5:
value is a function while a set was expected, at /Users/rsoeldner/work/haskell-nix-overlay/shell.nix:1:1
```

is there a need to pass hself to the app derivation like
```
app = hself.callPackage ./default.nix (inherit hself);
```

**Comment by sboosali** [comment]
assuming `default.nix` has the `cabal2nix` shape:

    { mkDerivation, lens, <etc> }: ...

the inputs are all provided by `callPackage`, and passing `hself` would be
an unexpected argument.

**Comment by rsoeldner** [comment]
@sboosali right, `default.nix` was created by `cabal2nix`.
I don't get the problem entering the shell

**Comment by Gabriel439** [comment]
@rsoeldner: It's because `callPackage` needs an extra `{}` argument, so the correct override section is actually:

```
  self: super:
  {
    haskellPackages = super.haskellPackages.override  {
      overrides = hself: hsuper:
      {   
        app = hself.callPackage ./default.nix {}; # ← Note the `{}`
      };  
    };  
  }
```
