### ISSUE TITLE
Re-running `nix-build release0.nix` does not incorporate changes

### ISSUE THREAD

**Issue by goertzenator** [Gabriel439/haskell-nix#78]
1. I run `nix-build release0.nix` in the first project and it works fine.
2. I edit `Main.hs` and change "Hello, world!" to something else.
3. I re-run `nix-build release0.nix` and it appear to rebuild things.
4. However, running the new executable `result/bin/project0` still prints "Hello, world!" instead of the new text that I saved in `Main.hs`.  Expected result is to print the new text.

**Comment by Gabriel439** [comment]
@goertzenator: I cannot reproduce the problem.  When I follow the steps you describe changes I made to `Main.hs` do affect the output of the `result/bin/project0` executable.

If you can push a branch with the changes that you made I can try reproducing on your branch

**Comment by goertzenator** [comment]
I checked out a new instance of the code and was also unable to reproduce the issue.  Must have been some sort of operator error the first go around... apologies for the distraction.

**Comment by Gabriel439** [comment]
No worries 🙂
