### ISSUE TITLE
Styx

### ISSUE THREAD

**Issue by jyp** [Gabriel439/haskell-nix#8]
I thought to mention the tool that I made to ease cabal/nix integration. 

https://github.com/jyp/styx

Feel free to mention it in this documentation project, and conversely please let me know if you see glaring holes in it. Incidentally, I've made a fork of intero that you may be interested in, because it does not require "stack":

https://github.com/jyp/dante

**Comment by Gabriel439** [comment]
Oh, I get it!  It's like the Nix-version of `stack` :)

Let me take a stab at using this and then I'll try to mention it in the guide.  It might take me a few days before I get to this, though

**Comment by jyp** [comment]
Thanks

**Comment by Gabriel439** [comment]
You're welcome!
