### ISSUE TITLE
$ nix-build release0.nix returns an error

### ISSUE THREAD

**Issue by jycappucino** [Gabriel439/haskell-nix#97]
https://github.com/Gabriel439/haskell-nix/blob/88a889d720667e44c87ad48cba23602339a29f24/project0/README.md?plain=1#L13

Hi,

Thank you for sharing this tutorial! I am a Haskell/cabal/nix noob and I am not a developer by profession - just trying out Haskell for fun. First off, I am liking how this tutorial is clearly explained. However, when I try "nix-build release0.nix", the terminal screams
**error: getting status of '/home/user/nix-test/release0.nix': No such file or directory**

Also if I try nix build release0.nix (no dash between nix and the build command) the terminal screams
**error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix command to override**

I am on Windows 10, and I have installed nix, ghc, and cabal using WSL2.

I hope to hear from you!

**Comment by jycappucino** [comment]
I tried **nix-shell --pure -p ghc cabal-install --run "cabal init"** and it worked. This is how I generated the release0.nix file.
Will now continue from here :-)

**Comment by jycappucino** [comment]
Found the answer to my second question:
Answer: $ nix-shell --packages ghc --run 'cabal init'

I think I will now be able to follow this tutorial! Thanks a lot!!!!!!

**Comment by Gabriel439** [comment]
You're welcome! 🙂
